#!/usr/bin/env bash
# charts/cnpg-projects renders one cnpg-cluster per project row, and Helm
# cannot loop over a subchart, so the cnpg-cluster templates are carried
# into cnpg-projects as named templates, generated from charts/cnpg-cluster
# (and its defaults). cnpg-cluster stays the single source; this script is
# the only writer of the generated files, and CI runs `check`.
#
#   hack/sync-cnpg-projects.sh          regenerate
#   hack/sync-cnpg-projects.sh check    fail when the generated files are stale
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
src="$root/charts/cnpg-cluster"
dst="$root/charts/cnpg-projects"
mode="${1:-write}"
out="$(mktemp -d)"
trap 'rm -rf "$out"' EXIT
mkdir -p "$out/templates" "$out/files"

banner='{{- /* GENERATED by hack/sync-cnpg-projects.sh from charts/cnpg-cluster: do not edit. */ -}}'

for f in "$src"/templates/*; do
  name="$(basename "$f")"
  if [ "$name" = _helpers.tpl ]; then
    { echo "$banner"; cat "$f"; } > "$out/templates/_cluster-helpers.tpl"
    continue
  fi
  base="${name%.yaml}"
  {
    echo "$banner"
    echo "{{- define \"cnpg-projects.cluster.$base\" -}}"
    cat "$f"
    echo
    echo "{{- end -}}"
  } > "$out/templates/_cluster-$base.tpl"
done

cp "$src/values.yaml" "$out/files/cnpg-cluster-defaults.yaml"

# The cnpg-project-platform objects the platform owns beside a Cluster
# another chart renders: the ScheduledBackup and the server TLS pair. Same
# inputs (scheduledBackups, serverTLS), same objects.
for pair in scheduledbackups servertls; do
  sed -e 's/cnpg-project-platform\./cnpg-projects.platform./g' \
    "$root/charts/cnpg-project-platform/templates/$pair.yaml" > "$out/templates/platform-$pair.yaml"
done
sed -e 's/cnpg-project-platform\./cnpg-projects.platform./g' \
  "$root/charts/cnpg-project-platform/templates/_helpers.tpl" > "$out/templates/_platform-helpers.tpl"

if [ "$mode" = check ]; then
  for g in "$out"/templates/* "$out"/files/*; do
    rel="${g#"$out"/}"
    cmp -s "$g" "$dst/$rel" || { echo "stale: charts/cnpg-projects/$rel (run hack/sync-cnpg-projects.sh)" >&2; exit 1; }
  done
  exit 0
fi

cp "$out"/templates/* "$dst/templates/"
cp "$out"/files/* "$dst/files/"
