{{- /* GENERATED by hack/sync-cnpg-projects.sh from charts/cnpg-cluster: do not edit. */ -}}
{{- define "cnpg-projects.cluster.trust" -}}
{{- /* Per-database client trust (values.yaml `trust`, `replication`).
Rendered by the PLATFORM, once per PostgreSQL cluster, because it owns
cluster-scoped objects and objects in cert-manager's namespace. Every
part is off by default. See docs/authentication.md. */}}
{{- $trust := .Values.trust | default dict }}
{{- $ca := $trust.ca | default dict }}
{{- $policy := $trust.policy | default dict }}
{{- $bundle := $trust.bundle | default dict }}
{{- $name := include "cnpg-cluster.trustName" . }}
{{- if $ca.enabled }}
{{- $tns := include "cnpg-cluster.trustNamespace" . }}
---
# The root of this database's client trust: a self-signed issuer whose
# only job is to sign the CA below.
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $name }}-selfsigned
  namespace: {{ $tns }}
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $name }}-ca
  namespace: {{ $tns }}
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  isCA: true
  commonName: {{ $name }} client CA
  secretName: {{ $name }}-ca
  duration: {{ $ca.duration | default "87600h" }}
  {{- with $ca.renewBefore }}
  renewBefore: {{ . }}
  {{- end }}
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Never
  issuerRef:
    name: {{ $name }}-selfsigned
    kind: Issuer
    group: cert-manager.io
---
# Cluster-scoped, so the product namespace can neither read the CA key
# (it lives in {{ $tns }}) nor sign with it: it can only ask, and the
# policy below decides.
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ $name }}
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ca:
    secretName: {{ $name }}-ca
{{- end }}
{{- if $policy.enabled }}
{{- $cns := list }}
{{- range ($policy.roles | default list) }}
{{- if hasPrefix "pg_" . }}
{{- fail (printf "trust.policy.roles: %q starts with pg_, which PostgreSQL reserves for its predefined roles" .) }}
{{- end }}
{{- $cns = append $cns . }}
{{- end }}
{{- $cns = append $cns "streaming_replica" }}
{{- $quoted := list }}
{{- range $cns }}{{- $quoted = append $quoted (printf "'%s'" .) }}{{- end }}
{{- $requester := $policy.requester | default dict }}
---
# approver-policy: the ONLY namespace that may request from this
# ClusterIssuer is {{ .Values.namespace }}, for client-auth certificates
# whose CN is one of the roles below (or streaming_replica), ECDSA only.
# Anything else is denied, including DNS/IP/URI/email SANs.
apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: {{ $name }}
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  allowed:
    commonName:
      required: true
      validations:
        - rule: {{ printf "self in [%s]" (join ", " $quoted) | quote }}
          message: "the common name must be one of the declared roles or streaming_replica"
    usages:
      - client auth
    isCA: false
  constraints:
    privateKey:
      algorithm: ECDSA
      minSize: 256
      maxSize: 521
  selector:
    issuerRef:
      name: {{ $name }}
      kind: ClusterIssuer
      group: cert-manager.io
    namespace:
      matchNames:
        - {{ .Values.namespace }}
---
# approver-policy approves a request only when its requester may `use`
# a policy that admits it. The requester of a Certificate is
# cert-manager itself; bound in this namespace only.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $name }}-policy-use
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: ["policy.cert-manager.io"]
    resources: ["certificaterequestpolicies"]
    verbs: ["use"]
    resourceNames: [{{ $name | quote }}]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}-policy-use
  namespace: {{ .Values.namespace }}
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $name }}-policy-use
subjects:
  - kind: ServiceAccount
    name: {{ $requester.name | default "cert-manager" }}
    namespace: {{ $requester.namespace | default "cert-manager" }}
{{- end }}
{{- if $bundle.enabled }}
{{- $tns := include "cnpg-cluster.trustNamespace" . }}
---
# trust-manager copies the CA certificate (never its key) into the
# database namespace as {{ .Values.clusterName }}-client-ca, where the
# Cluster's spec.certificates.clientCASecret reads it. A Bundle is
# cluster-scoped and its target Secret shares its name: the cluster name
# must therefore be unique across namespaces.
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: {{ .Values.clusterName }}-client-ca
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  sources:
    - secret:
        name: {{ $name }}-ca
        key: ca.crt
    {{- range ($bundle.extraCertificates | default list) }}
    - inLine: |
        {{- trim . | nindent 8 }}
    {{- end }}
  target:
    secret:
      key: ca.crt
      metadata:
        labels:
          cnpg.io/reload: "true"
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: {{ .Values.namespace }}
{{- end }}
{{- if include "cnpg-cluster.replicationEnabled" . }}
---
# The replication client certificate, from this database's own CA.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "cnpg-cluster.replicationSecretName" . }}
  namespace: {{ .Values.namespace }}
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  secretName: {{ include "cnpg-cluster.replicationSecretName" . }}
  commonName: streaming_replica
  usages:
    - client auth
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ $name }}
    kind: ClusterIssuer
    group: cert-manager.io
  secretTemplate:
    labels:
      cnpg.io/reload: "true"
{{- end }}
{{- /* Validates people and every map= even when nothing else renders. */}}
{{- $_ := include "cnpg-cluster.peopleRoles" . }}

{{- end -}}
