{{- /* GENERATED by hack/sync-cnpg-projects.sh from charts/cnpg-cluster: do not edit. */ -}}
{{- define "cnpg-projects.cluster.roles" -}}
{{- /* Application/technical roles. cert = operator-issued mTLS client
certificate in Secret {name}-client-cert (terminal state for apps).
password = the compatibility escape hatch: the bootstrap owner already
has the CNPG-generated {clusterName}-app Secret (declare no entry, or an
entry without passwordSecret); any OTHER password role must bring its
own kubernetes.io/basic-auth passwordSecret — the chart never generates
passwords (template-time randomness drifts under ArgoCD). Unknown auth
values fail the render. */}}
{{- range .Values.roles }}
{{- $auth := .auth | default "cert" }}
{{- if not (has $auth (list "cert" "password" "none")) }}
{{- fail (printf "role %s: auth must be cert|password|none (got %q)" .name $auth) }}
{{- end }}
{{- $isOwner := eq .name $.Values.bootstrap.initdb.owner }}
{{- if and (eq $auth "password") (not $isOwner) (not .passwordSecret) }}
{{- fail (printf "role %s: auth=password on a non-owner role requires passwordSecret (the chart never generates passwords)" .name) }}
{{- end }}
{{- if and $isOwner (eq $auth "none") }}
{{- fail (printf "role %s: the bootstrap owner cannot be auth=none" .name) }}
{{- end }}
{{- if not $isOwner }}
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: {{ $.Values.clusterName }}-{{ .name | replace "_" "-" }}
  namespace: {{ $.Values.namespace }}
spec:
  cluster:
    name: {{ $.Values.clusterName }}
  name: {{ .name | replace "-" "_" }}
  ensure: present
  login: {{ if hasKey . "login" }}{{ .login }}{{ else }}true{{ end }}
  {{- if eq $auth "cert" }}
  clientCertificate:
    enabled: true
  {{- else if eq $auth "password" }}
  passwordSecret:
    name: {{ .passwordSecret }}
  {{- end }}
  {{- with .inRoles }}
  inRoles:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  databaseRoleReclaimPolicy: retain
{{- end }}
{{- end }}

{{- /* peopleProject: the four roles a person's certificate selects by its
OU ({project}_admin|ddl|observer|read), by convention, in every project's
database. They hold no credential (auth none): only the people map's OU
rule reaches them, and a role must be LOGIN for PostgreSQL to admit the
connection. admin is the database owner's, never superuser. */}}
{{- with .Values.peopleProject }}
{{- $project := . }}
{{- range (list
  (dict "level" "admin" "in" (list $.Values.bootstrap.initdb.owner))
  (dict "level" "ddl" "in" (list "pg_read_all_data" "pg_write_all_data"))
  (dict "level" "observer" "in" (list))
  (dict "level" "read" "in" (list "pg_read_all_data"))) }}
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: {{ $.Values.clusterName }}-{{ $project | replace "_" "-" }}-{{ .level }}
  namespace: {{ $.Values.namespace }}
spec:
  cluster:
    name: {{ $.Values.clusterName }}
  name: {{ $project }}_{{ .level }}
  ensure: present
  login: true
  {{- with .in }}
  inRoles:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  databaseRoleReclaimPolicy: retain
{{- end }}
{{- end }}

{{- end -}}
